name: Assembly and Python Syntax Check

on: [push, pull_request]

jobs:
  assembly-and-python-syntax-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install flake8 for linting
      run: |
        python -m pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 assembler/assmbler.py assembler/main.py --count --select=E9,F63,F7,F82 --show-source --statistics

        - name: Run assembly script and check Python runtime errors for each file in testcases
        run: |
          set +e
          all_errors=0
          for file in testcases/*; do
            ./run_assembler.sh "$file" "output/$(basename "$file" .asm).out"
            if [ $? -ne 0 ]; then
              echo "Error occurred while processing $file"
              all_errors=1
            fi
          done
          if [ $all_errors -ne 0 ]; then
            exit 1
          fi
