name: Makefile CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Verilator
      run: sudo apt-get update && sudo apt-get install -y verilator

    - name: Run Makefile
      run: make all
